name: auto-release

on:
  push:
    branches: 
      - main
      - feature/**
  workflow_dispatch:

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git remote config
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name "tomyamkung"
          git config --list
      - name: Setup SSH
        uses: ./.github/actions/git-ssh-setup
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ secrets.SSH_KNOWNHOST }}
      - name: Generate netrc for Git
        uses: ./.github/actions/generate-netrc
        with:
          file-name: ${{ github.workspace }}/.netrc
          host-name: github.com
          user-name: tomyamkung
          pat: ${{ secrets.GITHUBPAT }}
      - name: Debug
        run: |
          cat .netrc
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r ${{ github.workspace }}/requirements.txt
      - name: Run Python
        run: python tools/auto-commit.py
        