name: auto-release

on:
  push:
    branches: 
      - main
      - feature/**
  workflow_dispatch:

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Generate netrc for Git
      #   uses: tomyamkung/shared-ci/generate-netrc@main
      #   with:
      #     file-name: ${{ github.workspace }}/.netrc
      #     host-name: github.com
      #     pat: ${{ secrets.GITHUBPAT }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r ${{ github.workspace }}/requirements.txt
      - name: Run Python
        run: python tools/auto-commit.py